### ISSUE TITLE
key binding

### ISSUE THREAD

**Issue by Ayzak** [andredla/DisplayColors#2]
Hi,

Can we add some key binding to show/hide display color ?

**Comment by andredla** [comment]
yes but i didint gave a very unique name so it may cross with some othe commands you may have,
you need to add this lines to your keybind in sublime:

{ "keys": ["ctrl+1"], "command": "displaycolors" },
{ "keys": ["ctrl+2"], "command": "clearall" },

first one shows
second one clear

set any keys you like! :)

**Comment by Ayzak** [comment]
Thx a lot ! Your script is exactly that I want !!! :D

**Comment by andredla** [comment]
Released a new version with real-time update on color change.
